### ISSUE TITLE
Traits in comet-extra

### ISSUE THREAD

**Issue by segeljakt** [Starlight-JS/comet#5]
I'm wondering, would it be possible to:
1. `impl Clone for comet_extra::alloc::string::String`
2. `impl Clone for comet_extra::alloc::vector::Vector`
3. `impl Collectable for comet_extra::alloc::vector::Vector`

I get around 1 & 2 by wrapping them in `Gc<T, _>`. I cannot get around 3 though.

**Comment by playXE** [comment]
`3` is possible. For 1 and 2 we would probably need to add `GcClone` trait into `comet` itself and a derive macro to make GcClone work. The main problem is that to clone GCed values we need to allocate memory for them
